version: "3"

services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    container_name: backend

  client:
    build: ./frontend
    ports:
      - "80:80"
    container_name: frontend

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: database
